name: Staticcheck

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run staticcheck
      uses: dominikh/staticcheck-action@v1.3.1
